//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRate", ReplyAction="http://tempuri.org/IService1/GetRateResponse")]
        string GetRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRate", ReplyAction="http://tempuri.org/IService1/GetRateResponse")]
        System.Threading.Tasks.Task<string> GetRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRates", ReplyAction="http://tempuri.org/IService1/GetAllRatesResponse")]
        string GetAllRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRates", ReplyAction="http://tempuri.org/IService1/GetAllRatesResponse")]
        System.Threading.Tasks.Task<string> GetAllRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHistoricalRates", ReplyAction="http://tempuri.org/IService1/GetHistoricalRatesResponse")]
        string GetHistoricalRates(string currencyCode, string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHistoricalRates", ReplyAction="http://tempuri.org/IService1/GetHistoricalRatesResponse")]
        System.Threading.Tasks.Task<string> GetHistoricalRatesAsync(string currencyCode, string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        string Register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUp", ReplyAction="http://tempuri.org/IService1/TopUpResponse")]
        string TopUp(string username, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUp", ReplyAction="http://tempuri.org/IService1/TopUpResponse")]
        System.Threading.Tasks.Task<string> TopUpAsync(string username, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        string GetBalance(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        System.Threading.Tasks.Task<string> GetBalanceAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        string BuyCurrency(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<string> BuyCurrencyAsync(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        string SellCurrency(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        System.Threading.Tasks.Task<string> SellCurrencyAsync(string username, string currencyCode, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionHistory", ReplyAction="http://tempuri.org/IService1/GetTransactionHistoryResponse")]
        string GetTransactionHistory(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransactionHistory", ReplyAction="http://tempuri.org/IService1/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<string> GetTransactionHistoryAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleClient.ServiceReference1.IService1>, ConsoleClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRate(string currencyCode) {
            return base.Channel.GetRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<string> GetRateAsync(string currencyCode) {
            return base.Channel.GetRateAsync(currencyCode);
        }
        
        public string GetAllRates() {
            return base.Channel.GetAllRates();
        }
        
        public System.Threading.Tasks.Task<string> GetAllRatesAsync() {
            return base.Channel.GetAllRatesAsync();
        }
        
        public string GetHistoricalRates(string currencyCode, string startDate, string endDate) {
            return base.Channel.GetHistoricalRates(currencyCode, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> GetHistoricalRatesAsync(string currencyCode, string startDate, string endDate) {
            return base.Channel.GetHistoricalRatesAsync(currencyCode, startDate, endDate);
        }
        
        public string Register(string username, string password) {
            return base.Channel.Register(username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string username, string password) {
            return base.Channel.RegisterAsync(username, password);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string TopUp(string username, decimal amount) {
            return base.Channel.TopUp(username, amount);
        }
        
        public System.Threading.Tasks.Task<string> TopUpAsync(string username, decimal amount) {
            return base.Channel.TopUpAsync(username, amount);
        }
        
        public string GetBalance(string username) {
            return base.Channel.GetBalance(username);
        }
        
        public System.Threading.Tasks.Task<string> GetBalanceAsync(string username) {
            return base.Channel.GetBalanceAsync(username);
        }
        
        public string BuyCurrency(string username, string currencyCode, decimal amount) {
            return base.Channel.BuyCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> BuyCurrencyAsync(string username, string currencyCode, decimal amount) {
            return base.Channel.BuyCurrencyAsync(username, currencyCode, amount);
        }
        
        public string SellCurrency(string username, string currencyCode, decimal amount) {
            return base.Channel.SellCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> SellCurrencyAsync(string username, string currencyCode, decimal amount) {
            return base.Channel.SellCurrencyAsync(username, currencyCode, amount);
        }
        
        public string GetTransactionHistory(string username) {
            return base.Channel.GetTransactionHistory(username);
        }
        
        public System.Threading.Tasks.Task<string> GetTransactionHistoryAsync(string username) {
            return base.Channel.GetTransactionHistoryAsync(username);
        }
    }
}
